name: Review Exercises
env:
  EXERCISES_PATH: ./exercises
on:
  pull_request:
    paths:
      - 'students/*/exercises/**'

jobs:    
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: git-04
      uses: ${{ EXERCISES_PATH }}/${{ EXERCISE_NAME }}/action.yaml@caio-test
      with:
        EXERCISE_NAME: git04

