name: Review Exercises
on:
  pull_request:
    paths:
      - 'students/**/*'

jobs:
  git04:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4

      - name: Review
        run: python ./exercises/git04/review.py

