name: Review Exercises
on:
  pull_request:
    paths:
      - 'students/**/*'

jobs:
  git04:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Review
        run: make review EXERCISE=git04

