name: reviewer-publish
on:
  pull_request:
    paths:
    - 'reviewer/exercises/git04/**/*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            devopsacademyau/reviewer
          tags: |
            type=ref,event=pr,prefix=git04-pr-
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          # push: ${{ github.event_name != 'pull_request' }}
          push: true
          context: ./reviewer
          file: ./reviewer/Dockerfile.python
          build-args: |
            EXERCISE=git04
          tags: ${{ steps.meta.outputs.tags }}